---
title: "ggplot 1"
author: "Pooja Mukund"
date: "10/5/2021"
output: github_document
---
```{r}
library(tidyverse)
```

```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USC00519397", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USC00519397 = "Waikiki_HA",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())
```


```{r}
weather_df %>%
  ggplot(aes(x = tmin, y=tmax, color=name)) +geom_point(alpha = 0.3) + geom_smooth(se = FALSE) +facet_grid(.~name)
```

```{r}
weather_df%>%
  ggplot(aes(x = date, y = tmax)) + geom_point()+facet_grid(.~name) + geom_smooth(se = FALSE)
```

```{r}
weather_df %>% 
  filter (name == 'CentralPark_NY') %>% 
  mutate(
    tmax - tmax * (9/5) + 32,
    tmin = tmin * (9/5)+32
  ) %>%
  ggplot(aes(x=tmin, y=tmax)) +
geom_point()
  
```
```{r}
weather_df%>%
  ggplot(aes(x = date, y = tmax, color=name)) + geom_smooth()
```

```{r}
weather_df %>%
  ggplot(aes(x=tmax)) + geom_density()
```

```{r}
weather_df%>%
  ggplot(aes(x = tmax, fill = name)) + 
  geom_density(alpha = 0.3)
```

```{r}
weather_df%>%
  ggplot(aes(x = name, y = tmax)) + 
  geom_violin()
```

```{r, fig.width=7, fig.height=5}
weather_df %>% 
  ggplot(aes(x= tmin, y = tmax, color = name)) + geom_point(alpha = 0.3)

```
## EDA Lecture 
```{r}
weather_df =  
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USC00519397", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USC00519397 = "Waikiki_HA",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10,
    month = lubridate::floor_date(date, unit = "month")) %>%
  select(name, id, everything())
```

